In [3]:
import pandas as pd
import numpy as np

In [4]:
# Load csv file with all the data
df = pd.read_csv("processed_data.csv")

In [5]:
df.head()

,csv_index,file_name,height_1,width_1,x_1,y_1,height_2,width_2,x_2,y_2,...,mouse2_rightear_x,mouse2_rightear_y,mouse2_leftHip_x,mouse2_leftHip_y,mouse2_rightHip_x,mouse2_rightHip_y,mouse2_tailBase_x,mouse2_tailBase_y,mouse2_tailEnd_x,mouse2_tailEnd_y
0,1.0,A_male_in_a_new_cage_face_view_3_2022-08-10_15...,-58.003070,92.601392,309.819097,240.139692,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1.0,A_male_in_a_new_cage_face_view_3_2022-08-10_15...,-133.929059,72.445612,348.037698,234.093237,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1.0,A_male_in_a_new_cage_face_view_3_2022-08-10_15...,-305.492165,255.763708,117.382338,339.519409,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1.0,A_male_in_a_new_cage_face_view_3_2022-08-10_15...,-157.179697,199.190860,169.095386,338.152066,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1.0,A_male_in_a_new_cage_face_view_3_2022-08-10_15...,-125.011190,300.026855,233.399193,338.445964,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN