In [3]:
import pandas as pd

In [4]:
# Load csv file with all the data
df = pd.read_csv("joined_data.csv")

In [6]:
df.head()

,csv_index,file_name,mouse1_topleft_x,mouse1_topleft_y,mouse1_rightdown_x,mouse1_rightdown_y,mouse1_nose_x,mouse1_nose_y,mouse1_leftear_x,mouse1_leftear_y,...,mouse2_rightear_x,mouse2_rightear_y,mouse2_leftHip_x,mouse2_leftHip_y,mouse2_rightHip_x,mouse2_rightHip_y,mouse2_tailBase_x,mouse2_tailBase_y,mouse2_tailEnd_x,mouse2_tailEnd_y
0,1.0,A_male_in_a_new_cage_face_view_3_2022-08-10_15...,309.819096782505,182.136622,402.420489,240.139692,316.340104,208.188458,327.316715,200.661639,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1.0,A_male_in_a_new_cage_face_view_3_2022-08-10_15...,348.03769787812223,100.164178,420.483310,234.093237,379.494345,110.649727,365.672485,125.901435,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1.0,A_male_in_a_new_cage_face_view_3_2022-08-10_15...,117.38233841437452,34.027243,373.146047,339.519409,143.080685,51.112113,158.491762,74.228728,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1.0,A_male_in_a_new_cage_face_view_3_2022-08-10_15...,169.09538588003477,180.972369,368.286246,338.152066,337.864369,236.021480,306.718162,203.426612,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1.0,A_male_in_a_new_cage_face_view_3_2022-08-10_15...,233.39919271055095,213.434775,533.426048,338.445964,510.209684,315.229601,495.029754,262.546314,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN